import { hashSync } from 'bcrypt';
import { User } from 'src/common/entities/user.entity';
import { SALT_LENGTH } from 'src/modules/update-password/constants';
import { Country } from 'src/modules/users/enums/country.enum';
import { UserRole } from 'src/modules/users/enums/user-role.enum';

const ONE_TO_EIGHT_PASSWORD = '12345678';

export const USERS_SEED: Partial<User>[] = [
  {
    email: 'superadmin@gmail.com',
    password: hashSync(process.env.ADMIN_DEFAULT_PASSWORD, SALT_LENGTH),
    firstName: 'SuperAdmin',
    lastName: 'SuperAdmin',
    phoneNumber: '+14575444474',
    dateOfBirth: '12/18/2005',
    isOpenToSeekerHomeLiving: false,
    role: UserRole.SuperAdmin,
    country: Country.Canada,
    state: '-',
    city: '-',
    zipCode: '-',
    address: '-',
    isVerified: true,
    otpCode: null,
    avatar: '',
    balance: 100000,
  },
  {
    email: 'admin@gmail.com',
    password: hashSync(process.env.ADMIN_DEFAULT_PASSWORD, SALT_LENGTH),
    firstName: 'Admin',
    lastName: 'Admin',
    phoneNumber: '+14575444488',
    dateOfBirth: '12/18/2005',
    isOpenToSeekerHomeLiving: false,
    role: UserRole.Admin,
    country: Country.USA,
    state: '-',
    city: '-',
    zipCode: '-',
    address: '-',
    isVerified: true,
    otpCode: null,
    avatar: '',
    balance: 100000,
  },
  {
    email: 'caregiver@gmail.com',
    password: hashSync(ONE_TO_EIGHT_PASSWORD, SALT_LENGTH),
    firstName: 'Caregiver',
    lastName: 'Caregiver',
    phoneNumber: '+14545464444',
    dateOfBirth: '12/18/2005',
    isOpenToSeekerHomeLiving: true,
    role: UserRole.Caregiver,
    country: Country.USA,
    state: 'Pennsylvania',
    city: 'Pennsylvania',
    zipCode: '40165',
    address: '486 Pennsylvania Dr. Shepherdsville, KY 40165',
    isVerified: true,
    otpCode: null,
    avatar: '',
    balance: 1000,
  },
  {
    email: 'seeker@gmail.com',
    password: hashSync(ONE_TO_EIGHT_PASSWORD, SALT_LENGTH),
    firstName: 'Seeker',
    lastName: 'Seeker',
    phoneNumber: '+14545474444',
    dateOfBirth: '12/18/2005',
    isOpenToSeekerHomeLiving: false,
    role: UserRole.Seeker,
    country: Country.USA,
    state: 'California',
    city: 'Los Angeles',
    zipCode: '90058',
    address: '2901 Alameda St, Los Angeles, CA 90058, USA',
    isVerified: true,
    otpCode: null,
    avatar: '',
    balance: 1000,
  },
];
