export enum ApiPath {
  Auth = 'auth',
  CompleteProfile = 'profile',
  CaregiverInfo = 'caregivers',
  Appointment = 'appointment',
  Diagnosis = 'diagnosis',
  Activity = 'activity',
  Capability = 'capability',
  ActivityLog = 'activity-log',
  User = 'user',
  Transactions = 'transactions',
  Notifications = 'notifications',
  AdminPanel = 'admin-panel',
  DefaultSeekerTask = 'default-seeker-task',
  SeekerReview = 'seeker-review',
}
